### ISSUE TITLE
Game Compatibility

### ISSUE THREAD

**Issue by Doubs115** [WootingKb/wooting-macros#147]
This might be a controversial topic as some games frown upon the use of macros, but I can also see this as a need for some people to play normally or because a game is bugged and you can't do it in the first place. My personal stance is it's should be up to the game dev to fix these bugs rather then patching out macros. That's just me though.

In my case I would like to use it in Valorant because there is a bug with raze that allows you to super jump. I personally have never been able to do this and probably never will in a competitive setting. As it stands currently it's impossible because macros straight up don't work on this game. Now my case is probably a bad example but another is a game like Dead By Daylight where people actively use macros to prevent repetitive hand injuries. 

Regardless of your use case , my question is how can we at least mitigate this? My initial thoughts are maybe making a database of games that work or don't. That might not be necessary but it's been done before. Another way to fix this is maybe the way the program interacts with keyboards/mice. I know nothing about that or the way Wootomation handles it but have heard about emulating keyboard and mouse drivers.

Lastly, another way that sometimes works is purely elevating the programs permissions. Currently as it stands this also doesn't work (in my case) but I also don't know if that's even implemented. 

If anyone can shine some light into the backend as it currently stands that would be nice.

**Comment by medzernik** [comment]
Using macros in Valorant, while they have a kernel-level anti-cheat running would be considered cheating. Making a community database might work, I'll keep that idea in mind. 

The application will eventually undergo a rewrite to support MacOS, the way it interacts with the OS and such is using a library that is crossplatform, but there are some bugs. I will most likely take a look at it closer once I get the rewrite underway.

Elevating permissions probably doesnt work because the grabber runs on a different thread. However, this will be changed as part of the thread fix of MacOS

**Comment by Doubs115** [comment]
Good to know!
